#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /usr/local/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: Tree

depend: Tree-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Tree $(@)

.PHONY: Tree
Tree:
	@$(MAKE) -f Makefile.Tree all

.PHONY: Tree-depend
Tree-depend:
	@$(MAKE) -f Makefile.Tree depend

project_name_list:
	@echo Tree
